### ISSUE TITLE
查询快递100接口报单号不存在

### ISSUE THREAD

**Issue by TheSaltwaterRoom** [wi1dcard/yii2-hejiang-express#1]
其实这一单是能查询到的，因为在curl之前加一下header头，大哥可以加一下吗

**Comment by wi1dcard** [comment]
你好，感谢关注。

请补充具体的上下文、出现的问题以及可能的解决方案；若有缺少头信息的情况，麻烦列出缺少的头信息。

**Comment by TheSaltwaterRoom** [comment]
'headers' => [
        'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36',
        'Accept'     => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    ]

加上这个header头才能请求成功，要不一直报单号不存在，我的建议可以做一个随机的user-agent和随机IP,如果接口请求太频繁就会被限制

**Comment by wi1dcard** [comment]
请提供测试单号。

**Comment by TheSaltwaterRoom** [comment]
3914799155871

**Comment by wi1dcard** [comment]
已经修复，Tag `v0.1.3`。

**Comment by TheSaltwaterRoom** [comment]
Good
